# Site settings
title: Coding with Cliff
header-img: img/home-bg.png
email: sclifford6262@gmail.com
copyright_name: scliff6262
description: > # this means to ignore newlines until "baseurl:"
  Pursuing a Career in Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: cliff914
github_username:  scliff6262
learn_profile: scliff6262
email_username: sclifford6262@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
