# Site settings
author: Sean Clifford 
title: Coding with Cliff
header-img: img/home-bg.png
email: sclifford6262@gmail.com
copyright_name: Sean Clifford 
description: > # this means to ignore newlines until "baseurl:"
  Javascript, React, and Rails
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  scliff6262

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
